# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4322cd0218268cc04ec69d1b387ddb62035ab71393df76ccce496bc467827abafd748298652775cfae9ae1173444b7bb2d1756e01f57a7052315e7eecf1ce009

test:
  secret_key_base: fa5c220d47b28da6042e426b431e4a51713388160af4ac5a181d7d02cc476426ed68d1107c7bd2854f18e5b37f102123460b7030643f1c82c25aa2ad2f1e4e5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
